receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug # For dev; use info or warn in prod
  otlp/jaeger: # Sending data to Jaeger
    endpoint: "jaeger:4317" # Jaeger's OTLP gRPC endpoint
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging] # For now, just log metrics
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging] # For now, just log logs

  extensions: [health_check, pprof, zpages]

extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
